version: "2"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: "app"
    depends_on:
      - db
    ports:
        - "8443:8443" # application
        - "9990:9990" # admin console

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: "db"
    ports:
      - "3306:3306"

    #    volumes:
    #      - ./src/main/resources/database/1-create_roles.sql:/docker-entrypoint-initdb.d/1-1-create_roles.sql
    #      - ./src/main/resources/database/2-create_database.sql:/docker-entrypoint-initdb.d/2-2-create_database.sql
    #      - ./src/main/resources/database/3-init_data.sql:/docker-entrypoint-initdb.d/3-3-init_data.sql
    #    environment:
    #      - MYSQL_ALLOW_EMPTY_PASSWORD=true

networks:
  default:
    driver: bridge