version: "2"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: "app"
    depends_on:
      - db
#    ports:
#        - "8443:8443" # application
#        - "9990:9990" # admin console
    expose:
      - "8080"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: "db"
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
      - db
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificate.crt:/etc/ssl/certs/nginx/certificate.crt
      - ./nginx/certificate.key:/etc/ssl/certs/nginx/certificate.key
    ports:
      - 80:80
      - 443:443

networks:
  default:
    driver: bridge