version: "2"

services:
  tua:
    image: "pawrob/wildfly_tua05:latest"
    container_name: "tua"
    depends_on:
      - db
    expose:
      - "8443"
      - "8080"

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: "db"
    expose:
      - "3306"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - tua
      - db
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificate.crt:/etc/ssl/certs/nginx/certificate.crt
      - ./nginx/certificate.key:/etc/ssl/certs/nginx/certificate.key
    ports:
      - 80:80
      - 443:443
networks:
  default:
    driver: bridge